/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Cores de ação dos ícones (contrastantes entre si)
        'action-view': '#2563eb',      // azul
        'action-download': '#16a34a',  // verde
        'action-visibility': '#ea580c', // laranja
        'action-rename': '#0891b2',    // ciano
        'surface-container-high': '#e5e5ef',
        error: '#ba1a1a',
        'surface-tint': '#1a3fff',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f2f2fc',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f2f2fc',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#2a3599',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-highest': '#e0e0ea',
        'secondary-fixed': '#dde0ff',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#bac3ff',
        'primary-fixed-dim': '#bac3ff',
        'on-primary-fixed': '#00006e',
        primary: '#1a3fff',
        'on-tertiary-fixed-variant': '#004f7a',
        'outline-variant': '#c4c4d4',
        'surface-variant': '#e0e0f5',
        'on-secondary-container': '#0a0f52',
        'tertiary-container': '#c8eaff',
        background: '#fafaff',
        'on-primary-fixed-variant': '#0026a8',
        'surface-dim': '#d8d8e6',
        'inverse-surface': '#2d2d3a',
        outline: '#737383',
        tertiary: '#0066bb',
        'primary-fixed': '#dde0ff',
        'tertiary-fixed': '#c8eaff',
        'on-surface-variant': '#444454',
        'surface-bright': '#fafaff',
        'secondary-container': '#dde0ff',
        'primary-container': '#dde0ff',
        'surface-container': '#ebebf5',
        'on-primary-container': '#00006e',
        'on-background': '#181824',
        'inverse-primary': '#bac3ff',
        'on-secondary-fixed': '#0a0f52',
        'on-surface': '#181824',
        'on-error-container': '#93000a',
        secondary: '#4455cc',
        'tertiary-fixed-dim': '#8acfff',
        'on-tertiary-fixed': '#001d35',
        'on-tertiary-container': '#001d35',
        surface: '#fafaff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        gutter: '24px',
        base: '4px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}

