/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#e4eade',
        error: '#ba1a1a',
        'surface-tint': '#006e20',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#ecf3e7',
        'on-secondary': '#ffffff',
        'surface-container-low': '#eff6e9',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#93000d',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-highest': '#dee5d9',
        'secondary-fixed': '#ffdad6',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#ffb4ab',
        'primary-fixed-dim': '#71dd76',
        'on-primary-fixed': '#002205',
        primary: '#006b1f',
        'on-tertiary-fixed-variant': '#004491',
        'outline-variant': '#becab9',
        'surface-variant': '#dee5d9',
        'on-secondary-container': '#fffbff',
        'tertiary-container': '#3673d1',
        background: '#f5fbef',
        'on-primary-fixed-variant': '#005316',
        'surface-dim': '#d6dcd0',
        'inverse-surface': '#2c322a',
        outline: '#6f7a6b',
        tertiary: '#0a59b6',
        'primary-fixed': '#8dfa8f',
        'tertiary-fixed': '#d7e2ff',
        'on-surface-variant': '#3f4a3c',
        'surface-bright': '#f5fbef',
        'secondary-container': '#de2c2b',
        'primary-container': '#0b872b',
        'surface-container': '#eaf0e4',
        'on-primary-container': '#f7fff1',
        'on-background': '#171d16',
        'inverse-primary': '#71dd76',
        'on-secondary-fixed': '#410002',
        'on-surface': '#171d16',
        'on-error-container': '#93000a',
        secondary: '#ba0816',
        'tertiary-fixed-dim': '#acc7ff',
        'on-tertiary-fixed': '#001a40',
        'on-tertiary-container': '#fefcff',
        surface: '#f5fbef',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '48px',
        gutter: '24px',
        base: '4px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}

